# src/ui/styling.py
# Copyright (c) 2025 Google. All rights reserved.

import json
import os
import sys
from typing import Literal
from PyQt6.QtWidgets import QApplication # Added import

import qdarktheme

# Define the valid theme names for type hinting and validation
Theme = Literal["dark", "light", "auto"]

def _get_settings_path() -> str:
    """Determines the path to the application's settings file."""
    app_name = "ProjectFileExporter"
    if sys.platform == "win32":
        config_dir = os.path.join(os.environ['APPDATA'], app_name)
    else:
        config_dir = os.path.join(os.path.expanduser('~'), '.config', app_name)
    
    os.makedirs(config_dir, exist_ok=True)
    return os.path.join(config_dir, "settings.json")

def save_theme_setting(theme: Theme):
    """Saves the chosen theme string to the settings file."""
    path = _get_settings_path()
    try:
        with open(path, "w") as f:
            json.dump({"theme": theme}, f)
    except IOError as e:
        print(f"Error saving theme setting: {e}")

def load_theme_setting() -> Theme:
    """Loads the chosen theme from the settings file."""
    path = _get_settings_path()
    if not os.path.exists(path):
        return "auto"
    
    try:
        with open(path, "r") as f:
            settings = json.load(f)
            theme = settings.get("theme", "auto")
            if theme in ["dark", "light", "auto"]:
                return theme
            return "auto" 
    except (json.JSONDecodeError, IOError):
        return "auto" 

def apply_theme(theme: Theme):
    """Applies the specified theme to the entire Qt application."""
    # 1. Apply the library theme
    qdarktheme.setup_theme(theme)
    
    # 2. Apply Custom Overrides
    # This manually forces tooltips to look correct regardless of OS quirks.
    # We appened this to the stylesheet generated by qdarktheme.
    custom_styles = """
    QToolTip {
        color: #ffffff;
        background-color: #2b2b2b;
        border: 1px solid #767676;
        padding: 4px;
        border-radius: 4px;
        opacity: 230; 
    }
    """
    
    app = QApplication.instance()
    if app:
        # Append our custom rules to the existing stylesheet
        current_sheet = app.styleSheet()
        app.setStyleSheet(current_sheet + custom_styles)

def setup_app_theme():
    """The main entry point for theming. Loads the saved theme and applies it."""
    current_theme = load_theme_setting()
    apply_theme(current_theme)